AddLevel(LEVELTYPE.SURVIVAL, {
    id="TMGCAVES",
    name="Caves on Land",
    desc= "Preset for using caves on Land",
    location = "forest",
    version = 3,
    overrides={
      task_set = "tmgcaves",
      keep_disconnected_tiles = false,
      roads = "never",
      layout_mode = "RestrictNodesByKey",
      start_location = "tmgcavestart",
      wormhole_prefab = "tentacle_pillar",
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        --"ChessSpot1",
        --"ChessSpot2",
        --"ChessSpot3",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})

AddLevel(LEVELTYPE.SURVIVAL, {
    id="C_PLUS_PLUS", -- Classic Plus
    name="Classic Plus",
    desc= "Default Plus with RoG turned off.",
    location = "forest",
    version = 3,
    overrides={
        task_set = "classic",
        start_location = "plus",
        boons = "often",
        spiders = "often",
        berrybush = "rare",
        carrot = "rare",
        rabbits = "rare",
        spring = "noseason",
        summer = "noseason",
        frograin = "never",
        wildfires = "never",
        bearger = "never",
        goosemoose = "never",
        dragonfly = "never",
        deciduousmonster = "never",
        houndmound = "never",
        buzzard = "never",
        catcoon = "never",
        moles = "never",
        lightninggoat = "never",
        rock_ice = "never",
        cactus = "never",
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        --"ChessSpot1",
        --"ChessSpot2",
        --"ChessSpot3",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})

AddLevel(LEVELTYPE.SURVIVAL, {
    id="FORESTLO", -- Lights Out Plus
    name="Forest-Only Lights out",
    desc= "Modded Lightout with a Forest-Only",
    location = "forest",
    version = 3,
    overrides={
      task_set = "TMGcreepyforest",
      start_location = "TMGLightsOut",
      day = "onlynight",
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        --"ChessSpot1",
        --"ChessSpot2",
        --"ChessSpot3",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})

AddLevel(LEVELTYPE.SURVIVAL, {
    id="INSPECTORMODWORLDGENLEVEL", -- My Preset for magic things.
    name="Gen+",
    desc= "A preset required for having some options work.",
    location = "forest",
    version = 3,
    overrides={
      --keep_disconnected_tiles = GetModConfigData("islandness"),
      --islands = function() if GetModConfigData("islandness") then return "true" end end or "never", --Using "or never" to let it not crash when islandness is set to false.
      --roads = GetModConfigData("disableRoads") or nil,
      --layout_mode = GetModConfigData("layoutmode"),
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        --"ChessSpot1",
        --"ChessSpot2",
        --"ChessSpot3",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})

AddLevel(LEVELTYPE.SURVIVAL, {
    id="TWOWORLDS", -- Two Worlds From Adventure Mode
    name="Two Worlds",
    desc= "Don't Starve Adventure mode: Two Worlds",
    location = "forest",
    version = 3,
    overrides={
        task_set = "TMGtwolands",
        start_location = "TMGbargainstart",
        day = "longday",
        --season_start = "autumn",
        season = "onlyautumn",
        roads = "never",
        bearger = "never",
        deerclops = "never",
        keep_disconnected_tiles = true, --This allows islands to persist
        islands = "always" --Setting islands to always will try to seperate every task. Requires keep_disconnected_tiles
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        --"ChessSpot1",
        --"ChessSpot2",
        --"ChessSpot3",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})

AddLevel(LEVELTYPE.SURVIVAL, {
    id = "ISLANDHOP", -- DS Adventure mode Archipelago
    name = "Archipelago",
    desc = "Don't Starve Island hop nostalgia.",
    location = "forest",
    version = 3,
    overrides = {
        task_set = "islandhopadventure",
        start_location = "thismeanswardst",
        --weather = {"rare", "default", "often"},
        roads = "never",
        islands = "always",
        keep_disconnected_tiles = true,
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})

AddLevel(LEVELTYPE.SURVIVAL, {
    id = "HUB", -- DS Adventure mode Archipelago
    name = "The Game is Afoot",
    desc = "Don't Starve Adventure mode: The Game is Afoot",
    location = "forest",
    version = 3,
    overrides = {
        task_set = "gameisafootadventure",
        start_location = "presummerstartdst",

        day = "longdusk",

        season_start = "winter",
        summer = "noseason",
        spring = "noseason",
        winter = "noseason",

        loop = "never",

        spiders = "often",

        bearger = "never",
        dragonfly = "never",
        goosemoose = "never",
        deerclops = "never",
    },
    ordered_story_setpieces = {
        "Sculptures_1",
        "Maxwell5",
    },
    numrandom_set_pieces = 4,
    random_set_pieces = {
        "Sculptures_2",
        "Sculptures_3",
        "Sculptures_4",
        "Sculptures_5",
        "Chessy_1",
        "Chessy_2",
        "Chessy_3",
        "Chessy_4",
        "Chessy_5",
        "Chessy_6",
        "Maxwell1",
        "Maxwell2",
        "Maxwell3",
        "Maxwell4",
        "Maxwell6",
        "Maxwell7",
        "Warzone_1",
        "Warzone_2",
        "Warzone_3",
    },
})
